[package]
name = "bridge-guest"
version = "0.1.0"
edition = "2024"

[dependencies]
risc0-zkvm = { version = "0.19", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
